# Generated by Django 5.0.6 on 2024-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_chatsession_last_active_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_type",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot")],
                default="user",
                max_length=10,
            ),
        ),
    ]
