# Generated by Django 5.0.6 on 2024-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_remove_document_url_document_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
