# Generated by Django 5.0.6 on 2024-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_alter_document_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
